version: '3.3'
networks:
    extnetwork:
        ipam:
            config:
                - subnet: 172.18.0.0/24
services:
    mysql:
        image: mysql:5.6
        container_name: mysql
        ports:
            - '3306:3306'
        environment:
            - MYSQL_ROOT_PASSWORD=123456
        volumes:
            - d:\Docker\mysql\conf.d:/etc/mysql/conf.d
            - d:\Docker\mysql\data:/var/lib/mysql
            - d:\Docker\logs:/var/log
        networks:
            extnetwork:
                ipv4_address: 172.18.0.2
    redis26:
        image: redis:2.6
        container_name: redis26
        ports:
            - '6380:6379'
        command: redis-server /etc/redis/redis.conf --appendonly yes
        volumes:
            - d:\Docker\redis26\redis.conf:/etc/redis/redis.conf
            - d:\Docker\redis26\data:/data
        networks:
            extnetwork:
                ipv4_address: 172.18.0.3
    redis28:
        image: redis:2.8
        container_name: redis28
        ports:
            - '6381:6379'
        command: redis-server /etc/redis/redis.conf --appendonly yes
        volumes:
            - d:\Docker\redis28\redis.conf:/etc/redis/redis.conf
            - d:\Docker\redis28\data:/data
        networks:
            extnetwork:
                ipv4_address: 172.18.0.4
    redis32:
        image: redis:3.2
        container_name: redis32
        ports:
            - '6379:6379'
        command: redis-server /etc/redis/redis.conf --appendonly yes
        volumes:
            - d:\Docker\redis32\redis.conf:/etc/redis/redis.conf
            - d:\Docker\redis32\data:/data
        networks:
            extnetwork:
                ipv4_address: 172.18.0.5
    mongo:
        image: mongo:3.4
        container_name: mongo
        ports:
            - '27017:27017'
        networks:
            extnetwork:
                ipv4_address: 172.18.0.6
    phpfpm54:
        # image: php:5.4-fpm
        image: 1758677739/phpfpm:5.4
        container_name: phpfpm54
        ports:
            - '9054:9000'
        volumes:
            - d:\Docker\www:/var/www/html
            - d:\Docker\php-fpm54:/usr/local/etc/php
            - d:\Docker\logs:/var/log
        networks:
            extnetwork:
                ipv4_address: 172.18.0.7
    phpfpm55:
        # image: php:5.5-fpm
        image: 1758677739/phpfpm:5.5
        container_name: phpfpm55
        ports:
            - '9055:9000'
        volumes:
            - d:\Docker\www:/var/www/html
            - d:\Docker\php-fpm55:/usr/local/etc/php
            - d:\Docker\logs:/var/log
        networks:
            extnetwork:
                ipv4_address: 172.18.0.8
    phpfpm56:
        # image: php:5.6-fpm
        image: 1758677739/phpfpm:5.6
        container_name: phpfpm56
        ports:
            - '9056:9000'
        volumes:
            - d:\Docker\www:/var/www/html
            - d:\Docker\php-fpm56:/usr/local/etc/php
            - d:\Docker\logs:/var/log
        networks:
            extnetwork:
                ipv4_address: 172.18.0.9
    phpfpm70:
        # image: php:7.0-fpm
        image: 1758677739/phpfpm:7.0
        container_name: phpfpm70
        ports:
            - '9070:9000'
        volumes:
            - d:\Docker\www:/var/www/html
            - d:\Docker\php-fpm70:/usr/local/etc/php
            - d:\Docker\logs:/var/log
        networks:
            extnetwork:
                ipv4_address: 172.18.0.10
    phpfpm71:
        # image: php:7.1-fpm
        image: 1758677739/phpfpm:7.1
        container_name: phpfpm71
        ports:
            - '9071:9000'
        volumes:
            - d:\Docker\www:/var/www/html
            - d:\Docker\php-fpm71:/usr/local/etc/php
            - d:\Docker\logs:/var/log
        networks:
            extnetwork:
                ipv4_address: 172.18.0.11
    phpfpm72:
        # image: php:7.2-fpm
        image: 1758677739/phpfpm:7.2
        container_name: phpfpm72
        ports:
            - '9072:9000'
        volumes:
            - d:\Docker\www:/var/www/html
            - d:\Docker\php-fpm72:/usr/local/etc/php
            - d:\Docker\logs:/var/log
        networks:
            extnetwork:
                ipv4_address: 172.18.0.12
    phpfpm73:
        # image: php:7.3-fpm
        image: 1758677739/phpfpm:7.3
        container_name: phpfpm73
        ports:
            - '9073:9000'
        volumes:
            - d:\Docker\www:/var/www/html
            - d:\Docker\php-fpm73:/usr/local/etc/php
            - d:\Docker\logs:/var/log
        networks:
            extnetwork:
                ipv4_address: 172.18.0.13
    phpfpm74:
        # image: php:7.4-fpm
        image: 1758677739/phpfpm:7.4
        container_name: phpfpm74
        ports:
            - '9074:9000'
        volumes:
            - d:\Docker\www:/var/www/html
            - d:\Docker\php-fpm74:/usr/local/etc/php
            - d:\Docker\logs:/var/log
        networks:
            extnetwork:
                ipv4_address: 172.18.0.14
    nginx:
        image: nginx
        container_name: nginx
        ports:
            - '80:80'
        depends_on:
            - phpfpm54
            - phpfpm55
            - phpfpm56
            - phpfpm73
        links:
            - phpfpm54
            - phpfpm55
            - phpfpm56
            - phpfpm70
            - phpfpm71
            - phpfpm72
            - phpfpm73
            - phpfpm74
        volumes:
            - d:\Docker\www:/var/www/html
            - d:\Docker\nginx\nginx.conf:/etc/nginx/nginx.conf
            - d:\Docker\nginx\conf.d:/etc/nginx/conf.d
            - d:\Docker\logs\nginx:/var/log/nginx
        networks:
            extnetwork:
                ipv4_address: 172.18.0.100
